version: '2'
services:
    db:
        image: mongo
    api:
        build:
            context: ./api
    webserver:        
        build:
            context: ./webserver
    lb:
        image: nginx
        volumes: 
            - ./loadBalancer/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "5000:80"
        links:
            - webserver